name: PR Schema Validation
on:
  pull_request:
    branches:
      - main

jobs:
  check-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod download
      - name: List modified files
        id: list_files
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > modified_files.txt
          cat modified_files.txt
      - name: Run schema verification
        run: |
          go run main.go modified_files.txt
